Add favicon for use in AUTH0
alphagov/forms-admin pull request #929
Opened 2024-02-06 16:00 UTC by thomasiles

The Auth0 login page doesn't have a favicon.

This commit copies the govuk favicon from the node_modules assets dir into the public folder so it has a static URL which auth0 can use.

It's called `public/auth-favicon.ico` rather than `favion.ico` to avoid being used in other contexts than Auth0.

We set the admin favicon through HTML. I think it's probably a good idea to duplicate `favicon.ico` for browsers and applications which check it rather than using the value set in the HTML.

This commit is only about getting an icon in Auth0 so doesn't touch that.

When the gov.uk icon updates, we need to update this file too.

```bash
cp node_modules/govuk-frontend/dist/govuk/assets/images/favicon.ico public/ auth-favicon.ico
```

A card to update the auth0 terraform will follow. 

### What problem does this pull request solve?

Trello card: https://trello.com/c/FlmddpGh/1356-add-favicon-to-auth0

### Things to consider when reviewing

- Ensure that you consider the wider context.
- Does it work when run on your machine?
- Is it clear what the code is doing?
- Do the commit messages explain why the changes were made?
- Are there all the unit tests needed?
- Has all relevant documentation been updated?

2024-02-08 09:30 UTC, DavidBiddle approved these changes
Nice! 🎉

2024-02-12 08:13 UTC, lfdebrux approved these changes

2024-02-20 06:33 UTC, lfdebrux requested changes
This should be changed to the Tudor crown now

2024-02-20 09:15 UTC, thomasiles commented
It's now got the latest crown, has been rebased to main as has the changes to the terraform.

2024-02-20 09:18 UTC, lfdebrux approved these changes

2024-02-20 09:23 UTC, merged